spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: JongWon1408!
    url: jdbc:mysql://localhost:3306/testDB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true # 로그에 쿼리 이쁘게 해줌
        user_sql_comments: true # 쿼리나갈때 주석 보여줌
